plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.4'
    id("io.samjingwen.code-generator") version "1.0"
}

group = 'com.example'
version = '1.0-SNAPSHOT'

sourceCompatibility = '17'
targetCompatibility = '17'


repositories {
    mavenCentral()
}

dependencies {
    implementation platform('software.amazon.awssdk:bom:2.31.58')  // BOM for consistent version management
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.jcraft:jsch:0.1.55'

    implementation 'software.amazon.awssdk:transfer:2.31.58'
    implementation 'software.amazon.awssdk:s3:2.31.58'  // Updated to 2.31.58
    implementation 'software.amazon.awssdk:sts:2.31.58'  // Updated to 2.31.58
    implementation 'software.amazon.awssdk:secretsmanager:2.31.58'  // Updated to 2.31.58
    implementation 'software.amazon.awssdk:auth:2.31.58'  // Updated to 2.31.58
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
}

